ttp {

    upstream all {
        # O Docker Swarm resolve esse nome para os IPs dos containers automaticamente
        server site-replicado:80;
    }

    server {
         listen 4500;
         location / {
              proxy_pass http://all/;
         }
    }

}

events { }
